name: CI-autotools

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - '.gitignore'
      - '.github/FUNDING.yml'
      - '.github/workflows/ci-meson.yml'
      - '.github/workflows/ci-cmake.yml'

  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.github/FUNDING.yml'
      - '.github/workflows/ci-meson.yml'
      - '.github/workflows/ci-cmake.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout setup-cross-os2emx
        uses: actions/checkout@v6

      - name: Setup cross-os2emx
        uses: ./.

      - name: Checkout liba52
        uses: actions/checkout@v6
        with:
          repository: 'komh/liba52-os2'
          ref: '0.7.4-os2'

      - name: Bootstrap
        run: |
          autoreconf -fvi

      - name: Configure
        run: |
          chmod +x configure
          mkdir build
          cd build
          ../configure --host=i686-pc-os2-emx --prefix="/@unixroot/usr" \
                       --enable-shared --enable-static CFLAGS="-g -O2 -std=c99"

      - name: Build
        run: |
          make -C build

      - name: Install
        run: |
          make -C build install DESTDIR="${{ github.workspace }}/liba52"
