name: CI-cmake

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - '.gitignore'
      - '.github/FUNDING.yml'
      - '.github/workflows/ci-autotools.yml'
      - '.github/workflows/ci-meson.yml'

  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.github/FUNDING.yml'
      - '.github/workflows/ci-autotools.yml'
      - '.github/workflows/ci-meson.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}

  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout setup-cross-os2emx
        uses: actions/checkout@v6

      - name: Setup cross-os2emx
        uses: ./.
        with:
          use-exp-rpm: true
          rpm-arch: 'pentium4'
          rpm-deps: |
            zlib-devel
            bzip2-devel

          zip-deps: |
            https://github.com/komh/libpng-os2/releases/download/1.6.28-os2-r1/libpng-1.6.28.zip

      - name: Checkout FreeType2
        uses: actions/checkout@v6
        with:
          repository: 'komh/freetype2-os2'

      - name: Setup build
        run: |
          mkdir build
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=/@unixroot/usr -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="$OS2EMX_CMAKE_TOOLCHAIN_FILE"

      - name: Build
        run: |
          ninja -C build

      - name: Install
        run: |
          DESTDIR="${{ github.workspace }}/freetype2" ninja -C build install
