name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Release with notes
        uses: softprops/action-gh-release@v2
        with:
          name: Setup-cross-os2emx ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update_tag:
    needs: release
    uses: ./.github/workflows/update-tag.yml
    with:
      tag_name: ${{ github.ref_name }}
